### ISSUE TITLE
use proxychains 

### ISSUE THREAD

**Issue by RyanRong** [alexkimxyz/nsfw_data_scrapper#11]
nsfw_data_scrapper/scripts$
proxychains bash ./1_get_urls.sh 
ProxyChains-3.1 (http://proxychains.sf.net)
Getting images for class: neutral
https://www.reddit.com/r/mildlypenis/top/?t=all
Loaded /media/ryan/data/workspace/nsfw_data_scrapper/scripts/rip.properties
Loaded log4j.properties
Initialized ripme v1.7.74
|DNS-request| www.reddit.com 
|S-chain|-<>-127.0.0.1:1080-<><>-4.2.2.2:53-<><>-OK
|DNS-response| www.reddit.com is 151.101.41.140
Error while loading https://www.reddit.com/r/mildlypenis/top/.json?t=all
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:449)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
	at com.rarchives.ripme.utils.Http.response(Http.java:130)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getJsonArrayFromURL(RedditRipper.java:141)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:88)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:77)
	at com.rarchives.ripme.App.rip(App.java:99)
	at com.rarchives.ripme.App.ripURL(App.java:265)
	at com.rarchives.ripme.App.handleArguments(App.java:248)
	at com.rarchives.ripme.App.main(App.java:74)
[!] Error while ripping URL https://www.reddit.com/r/mildlypenis/top/?t=all
java.io.IOException: Failed to load https://www.reddit.com/r/mildlypenis/top/.json?t=all after 1 attempts
	at com.rarchives.ripme.utils.Http.response(Http.java:137)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getJsonArrayFromURL(RedditRipper.java:141)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:88)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:77)
	at com.rarchives.ripme.App.rip(App.java:99)
	at com.rarchives.ripme.App.ripURL(App.java:265)
	at com.rarchives.ripme.App.handleArguments(App.java:248)
	at com.rarchives.ripme.App.main(App.java:74)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:449)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
	at com.rarchives.ripme.utils.Http.response(Http.java:130)
	... 7 more

**Comment by alex000kim** [comment]
Hi @RyanRong, care to elaborate?

**Comment by ParmuSingh** [comment]
Seems like you're running the first script which you don't need to run cause /raw_data/ already has its output.

Also, if you're using windows, make sure you have Bash and Wget installed.

**Comment by RyanRong** [comment]
@alexkimxyz 
OS:ubuntu 18.4
Anaconda2,
when i run  bash ./1_get_urls.sh
@ParmuSingh 
i'm sure i have bash and wget installed.

**Comment by ghost** [comment]
> java.net.SocketException: Connection reset

**Comment by ParmuSingh** [comment]
Huh. Maybe a port is being used by some other application...?

**Comment by ghost** [comment]
Just something (firewall or the target website) don't want you download the content.

Solution: 
- Slow down the request speed if possible
- Use a proxy server (or just run script on a proxy server)

@ParmuSingh https://en.m.wikipedia.org/wiki/TCP_reset_attack
