### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by caopengfei** [alexkimxyz/nsfw_data_scrapper#40]
Getting images for class: neutral
https://www.reddit.com/r/mildlypenis/top/?t=all
Loaded /root/.config/ripme/rip.properties
Loaded log4j.properties
Initialized ripme v1.7.74
[+] Creating directory: ./raw_data/neutral/reddit_sub_mildlypenis
Error while loading https://www.reddit.com/r/mildlypenis/top/.json?t=all
javax.net.ssl.SSLException: Read timed out
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:320)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:258)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:137)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:168)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:449)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
	at com.rarchives.ripme.utils.Http.response(Http.java:130)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getJsonArrayFromURL(RedditRipper.java:141)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:88)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:77)
	at com.rarchives.ripme.App.rip(App.java:99)
	at com.rarchives.ripme.App.ripURL(App.java:265)
	at com.rarchives.ripme.App.handleArguments(App.java:248)
	at com.rarchives.ripme.App.main(App.java:74)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:165)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
	... 17 more

**Comment by caopengfei** [comment]
config docker with ：
https://docs.docker.com/network/proxy/#configure-the-docker-client
